global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
           - alertmanager:9093

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "grafana"
    static_configs:
      - targets: ["grafana:3000"]

  - job_name: "renderer"
    static_configs:
      - targets: ["renderer:8081"]

  - job_name: "minio"
    metrics_path: "/minio/v2/metrics/cluster"
    static_configs:
      - targets: ["s3:9000"]

  - job_name: "alertmanager"
    static_configs:
      - targets: ["alertmanager:9093"]