{
 "title": "overview",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "alertmanager",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "alertmanager_alerts" }
   ]
  },
  {
   "title": "grafana alerts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "grafana_alerting_active_alerts" }
   ]
  },
  {
   "title": "minio objects",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_bucket_usage_object_total"
    }
   ]
  },
  {
   "title": "rendering duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(grafana_image_renderer_service_http_request_duration_seconds_sum[1m]) /\nrate(grafana_image_renderer_service_http_request_duration_seconds_count[1m])"
    }
   ]
  },
  {
   "title": "up",
   "type": "grafana-polystat-panel",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 8 },
   "targets": [
    { "expr": "up", "legendFormat": "{{ job }}" }
   ]
  }
 ]
}